In [11]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("data/sql-murder-mystery.db")
cursor= connection.cursor()

def get_df(query:str)->pd.DataFrame:
    pd.set_option('display.max_colwidth', None)
    resp=cursor.execute(query)
    col = [d[0] for d in cursor.description]
    return(pd.DataFrame(resp, columns = col))

In [12]:
query='''
SELECT type, city, description
FROM crime_scene_report
WHERE date=20180115 and type="murder" and city="SQL City"'''
get_df(query=query)

,type,city,description
0,murder,SQL City,"Security footage shows that there were 2 witnesses. The first witness lives at the last house on ""Northwestern Dr"". The second witness, named Annabel, lives somewhere on ""Franklin Ave""."

In [14]:
query='''
SELECT id , name, address_number
FROM person
WHERE address_street_name= "Northwestern Dr"
ORDER BY address_number DESC
'''
get_df(query)

       id                  name  address_number
0   14887        Morty Schapiro            4919
1   17729        Lasonya Wildey            3824
2   53890        Sophie Tiberio            3755
3   73368        Torie Thalmann            3697
4   96595         Coretta Cubie            3631
5   19420           Cody Schiel            3524
6   93509        Emmitt Aceuedo            3491
7   87456   Leonora Wolfsberger            3483
8   36378        Freddie Ellzey            3449
9   53076           Boris Bijou            3327
10  28360        Rashad Cascone            3212
11  23044          Val Portlock            3143
12  51114     Christena Saffell            3055
13  68690            Yer Modest            3046
14  44004           Alison Eska            2951
15  98593           Jonah Toner            2947
16  59307          Cyril Yongue            2903
17  34155      Allyson Lazenson            2840
18  90397     Dionna Kranwinkle            2678
19  54564         Sammie Sengun            2590
20  53699      Christian Pagano            2585
21  34352    Vincenza Burkhardt            2512
22  80921       Donovan Yackley            2386
23  96178           Galina Khuu            2183
24  81885         Kurtis Masuda            2108
25  88423           Teri Ehrich            1879
26  51552           Bonita Knie            1726
27  72076     Courtney Bordeaux            1707
28  81052     Calvin Czelusniak            1516
29  71924        Laurie Scronce            1418
30  23960  Kristopher Lagerberg            1392
31  70485     Andera Kostelecky            1252
32  22239         Dusty Sigafus            1125
33  18376              Josh Shi            1091
34  29608       Willetta Lurvey            1028
35  33415         Homer Simpson             981
36  55130        Shiloh Huntoon             951
37  44542        Ivory Mcgrevey             897
38  99826          Ivy Kazarian             892
39  25615         Olevia Morena             812
40  40760          Renata Faver             745
41  10010             Muoi Cary             741
42  39688            Abe Roeker             689
43  26758      Angelena Billman             629
44  75484          Del Tacderen             607
45  12711        Norman Apolito             599
46  85280             Donn Duin             540
47  40336       Fredia Billeter             404
48  15171          Weldon Penso             311
49  89906       Kinsey Erickson             309

In [15]:
query='''
SELECT id , name , address_street_name
FROM person
WHERE name LIKE "%Annabell%"
'''
get_df(query)

      id                name address_street_name
0  78354      Annabell Siona       Whitewater Dr
1  78799  Annabell Droneburg        W Natalie Dr
2  86541   Annabell Zwilling            Patti Rd

In [16]:
query='''
select transcript
from interview
where person_id=14887
'''
get_df(query)

                                                                                                                                                                                                                        transcript
0  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

In [17]:
query='''
select F.id, F.person_id, F.name, P.license_id, D.plate_number
from get_fit_now_member as F
left JOIN person as P
on F.person_id = P.id
left join drivers_license as D
on P.license_id=D.id
where F.id like "48Z%" and F.membership_status="gold" and D.plate_number like "%H42W%"
'''
get_df(query)

      id  person_id           name  license_id plate_number
0  48Z55      67318  Jeremy Bowers      423327       0H42W2

In [18]:
query='''
select transcript
from interview
where person_id=67318
'''
get_df(query)

                                                                                                                                                                                                                                           transcript
0  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n

In [19]:
query='''
select P.name, P.id, C.event_name
from drivers_license as D
left join person as P
on D.id=P.license_id
left join facebook_event_checkin as C
on P.id=C.person_id
where D.hair_color="red" and D.car_make="Tesla" and D.height>=65 and D.height<=67
group by P.id
'''
get_df(query)

               name     id            event_name
0          Red Korb  78881                   NaN
1     Regina George  90700                   NaN
2  Miranda Priestly  99716  SQL Symphony Concert

In [20]:
query='''
select transcript
from interview
where person_id=99716
'''
get_df(query)

Empty DataFrame
Columns: [transcript]
Index: []

No data returned

## Miranda Priestly asesina

```
INSERT INTO solution VALUES (1, 'Miranda Priestly');
    SELECT value FROM solution;

```

In [23]:
cursor.execute('INSERT INTO solution VALUES (1, "Miranda Priestly")')

In [24]:
get_df('SELECT value FROM solution;')

                                                                                                                                                          value
0  Congrats, you found the brains behind the murder! Everyone in SQL City hails you as the greatest SQL detective of all time. Time to break out the champagne!